settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.tomaj.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: dennikn
    name: dennikn.sk
    url: 'https://dennikn.sk'
    method: GET
    expectStatus: 200

  - id: predplatne.dennikn.sk
    name: Predplatne Dennikn.sk
    url: 'https://predplatne.dennikn.sk/subscriptions/'
    method: GET
    expectStatus: 200

  - id: tyzden
    name: tyzden.sk
    url: 'https://tyzden.sk'
    method: GET
    expectStatus: 200

  - id: crm.dennikn.sk
    name: Predplatne tyzden.sk
    url: 'https://crm.tyzden.sk/sign/in/'
    method: GET
    expectStatus: 200
    
  - id: tomaj-sk # unique identifier
    name: tomaj.sk
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://tomaj.sk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
